### ISSUE TITLE
Chick numbers mysteriously fluctuate

### ISSUE THREAD

**Issue by bjoring** [melizalab/django-bird-colony#21]
Despite a consistent number of chicks assigned to a location, nest check numbers vary day to day
![18CF509C-4E73-4D30-A40C-CE5DD564A238](https://user-images.githubusercontent.com/9036425/73091741-11f6bf00-3ea9-11ea-8e08-664235d7d3be.jpeg)

**Comment by dmeliza** [comment]
This appears to be occurring because of an error in the manager that finds the latest event for each animal; the events are sorted by date, but if two events occurred on the same day in different locations, the older event may be retrieved and thus the bird mistakenly assigned to the wrong location.
