### ISSUE TITLE
can't query database for a list of birds at a location

### ISSUE THREAD

**Issue by bjoring** [melizalab/django-bird-colony#4]
It would be nice to be able to query the database for all the birds or a subset of birds at a particular location (e.g. all living, male birds in room xxx)

**Comment by dmeliza** [comment]
Another query or view that might be useful is all unreserved birds (or all birds reserved by a specific person)

**Comment by dmeliza** [comment]
This turns out to be difficult to implement because getting the last location of a bird requires some SQL trickery that I can't figure out how to implement in the django object model. To get the last location, you have to join the birds table with only the rows in the events table that are the last for each bird.

What I've done in the latest version is add a column to show the last location, which should give you some help in locating birds in colonies of relatively small size.

**Comment by dmeliza** [comment]
This is essentially implemented by the new location summary, which was added in 2aa935447058f9373de2fdc7cc3e594ceed0c7f1.
