### ISSUE TITLE
Server Error 500 when submitting new nest check

### ISSUE THREAD

**Issue by bpqle** [melizalab/django-bird-colony#42]
After filling in the nest location information, upon clicking "Submit Nest Check" I get a server 500 error.

Related errors/information:
 - The top 3 listed pairings do not have their location pairings listed, despite the birds existing in the nest locations individually.
 - Nest location L8 still appears with a pairing and 8 eggs, despite the pair being retired, separated and moved elsewhere the day prior (6/14/24). My guess is that the eggs in the nest weren't deleted.
 - Lastly, despite not being able to submit the nest check for 6/15/24, the summary breeding page still shows a 6/15/24 report.

**Comment by dmeliza** [comment]
Looks like several things contributing to the error.

- The location is showing as None because the view calculates the location on the first date of the report. In this case, 6/13/24. If a pair was created after that date, then it shows up in the list but the location is None, which is what's causing the form submission to throw an error.

- The issue with L8 is similar but reversed. The pairing ended on 6/14, so it's showing up in the list. This might be appropriate for the breeding report but not for the form. Will need to add some logic to exclude closed pairs from the form, but it shouldn't cause an error so it's a lower priority.
